#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int read_bitinfo(const uint32_t* bitinfo);
int read_bitstream_userid(const uint32_t* bitinfo);

int main(int argc, char* argv[])
{
    int opt;
    int read_userid = 0;
    char* coe_file;
    while ((opt = getopt(argc, argv, "f:u")) != -1) {
        switch (opt) {
            case 'u':
                read_userid = 1;
                break;
            case 'f':
                coe_file = optarg;
                break;
            case '?':
                if (optopt == 'f') fprintf(stderr, "Option -%c requires a valid coe file.\n", optopt);
                return 1;
            default:
                abort();
        }
    }

    if (coe_file == NULL) {
        fprintf(stderr, "Usage: %s -f <coe file> [-u]\n", argv[0]);
        return 1;
    }

    FILE* fp = fopen(coe_file, "r");
    if (fp == NULL) {
        fprintf(stderr, "Error opening file %s\n", coe_file);
        perror("errno");
        return 1;
    }

    // Max 4K
    uint32_t bitinfo[1024];
    char header[1024];

    // This implementation assumes the coe has been generated by AIT, with the first two lines being headers
    fscanf(fp, "%s", header);
    fscanf(fp, "%s", header);

    int i = 0;
    uint32_t val;

    while (fscanf(fp, "%X", &val) == 1) {
        if (i == 1024) {
            fprintf(stderr, "More values than expected: %d\n", i);
            fclose(fp);
            return 1;
        }
        bitinfo[i++] = val;
    }

    int ret;
    if (read_userid) {
        ret = read_bitstream_userid(bitinfo);
    } else {
        ret = read_bitinfo(bitinfo);
    }

    fclose(fp);
    return ret;
}
